parameters:
- name: REPO_NAME
  type: string
- name: IGNORE_STYLE
  type: boolean

jobs:
- job: flake8
  pool:
    vmImage: 'ubuntu-20.04'
  continueOnError: ${{ parameters.IGNORE_STYLE }}
  strategy:
    matrix:
      'python37':
        PYTHON_VERSION: '3.7'
      'python38':
        PYTHON_VERSION: '3.8'
  steps:
  - checkout: self
  - checkout: azure_template
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
  - script: |
      cd ${{ parameters.REPO_NAME }}
      python3 -m pip install -U pip
      pip3 install flake8==3.8.4

      if [[ -f ".flake8" ]]; then
        export FL8=.flake8-project
        mv .flake8 $FL8; # rename the file from code repo; should have higher precedence in merge
      fi
      ls
      cp ../.github/.flake8 .

      if [[ -f "$FL8" ]]; then # combine the exclude entries from both config files
          cp ../.github/azure/combine-exclude.py .;
          python3 combine-exclude.py $FL8;
          python3 -m flake8 . --append-config $FL8 --count --show-source --statistics;
          echo "done"
          cat $FL8
      else
          python3 -m flake8 . --count --show-source --statistics;
      fi

- job: black
  pool:
    vmImage: 'ubuntu-20.04'
  continueOnError: ${{ parameters.IGNORE_STYLE }}
  strategy:
    matrix:
      'python37':
        PYTHON_VERSION: '3.7'
      'python38':
        PYTHON_VERSION: '3.8'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
  - script: |
      python3 --version
      cd ${{ parameters.REPO_NAME }}
      python3 -m pip install -U pip
      pip3 install black==20.8b1
      python3 -m black . --check --diff -l 120
