parameters:
- name: REPO_NAME
  type: string
- name: IGNORE_STYLE
  type: boolean
  default: false
- name: COMPLEX
  type: boolean
  default: false
- name: GCC_CONFIG
  type: string
  default: empty
- name: INTEL_CONFIG
  type: string
  default: empty
- name: PRE_BUILD
  type: string
  default: .github/pre_build.sh
- name: BUILD_REAL
  type: string
  default: .github/build_real.sh
- name: TEST_REAL
  type: string
  default: .github/test_real.sh
- name: BUILD_COMPLEX
  type: string
  default: .github/build_complex.sh
- name: TEST_COMPLEX
  type: string
  default: .github/test_complex.sh
- name: IMAGE
  type: string
  default: public
- name: PYPI
  type: boolean
  default: false
- name: SKIP_TESTS
  type: boolean
  default: false
- name: TIMEOUT
  type: number
  default: 0

stages:
- stage: Test_Real
  dependsOn: []
  displayName: Test Real
  condition: not(${{ parameters.SKIP_TESTS }})
  jobs:
  - template: azure_build.yaml
    parameters:
      REPO_NAME: ${{ parameters.REPO_NAME }}
      GCC_CONFIG: ${{ parameters.GCC_CONFIG }}
      INTEL_CONFIG: ${{ parameters.INTEL_CONFIG }}
      PRE_BUILD: ${{ parameters.PRE_BUILD }}
      BUILD: ${{ parameters.BUILD_REAL }}
      TEST: ${{ parameters.TEST_REAL }}
      IMAGE: ${{ parameters.IMAGE }}
      TIMEOUT: ${{ parameters.TIMEOUT }}

- stage: Test_Complex
  dependsOn: []
  displayName: Test Complex
  condition: and(eq(${{ parameters.COMPLEX }}, true), not(${{ parameters.SKIP_TESTS }}))
  jobs:
  - template: azure_build.yaml
    parameters:
      REPO_NAME: ${{ parameters.REPO_NAME }}
      GCC_CONFIG: ${{ parameters.GCC_CONFIG }}
      INTEL_CONFIG: ${{ parameters.INTEL_CONFIG }}
      PRE_BUILD: ${{ parameters.PRE_BUILD }}
      BUILD: ${{ parameters.BUILD_COMPLEX }}
      TEST: ${{ parameters.TEST_COMPLEX }}
      IMAGE: ${{ parameters.IMAGE }}
      TIMEOUT: ${{ parameters.TIMEOUT }}

- stage: Style
  dependsOn: []
  displayName: Style
  condition: not(${{ parameters.SKIP_TESTS }})
  jobs:
  - template: azure_style.yaml
    parameters:
      REPO_NAME: ${{ parameters.REPO_NAME }}
      IGNORE_STYLE: ${{ parameters.IGNORE_STYLE }}

# - stage:
#   dependsOn:
#   - Test_Real
#   # - Test_Complex address at later date (if needed)
#   - Style
#   displayName: PyPI
#   condition: and(succeeded(), eq(${{ parameters.PYPI }}, true), contains(variables['build.sourceBranch'], 'tags'))
#   jobs:
#   - template: azure_pypi.yaml
#     parameters:
#      REPO_NAME: ${{ parameters.REPO_NAME }}