parameters:
  - name: REPO_NAME
    type: string
  - name: TAPENADE
    type: boolean
    default: false
  - name: TAPENADE_SCRIPT
    type: string
    default: .github/build_tapenade.sh
  - name: TAPENADE_VERSION
    type: string
    default: 3.10

jobs:
  - job: tapenade
    pool:
      vmImage: "ubuntu-20.04"
    condition: ${{ parameters.TAPENADE }}
    steps:
      - checkout: azure_template
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: "8"
          jdkArchitectureOption: "x64"
          jdkSourceOption: "PreInstalled"
      - script: |
          if [[ "${{ parameters.TAPENADE_VERSION }}" == "3.10" ]]; then
            export TAPENADE_URL=http://umich.edu/~mdolaboratory/misc/tapenade3.10.tar
            export TAPENADE_HOME=$(pwd)/tapenade${{ parameters.TAPENADE_VERSION }}/bin
          elif [[ "${{ parameters.TAPENADE_VERSION }}" == "3.16" ]]; then
            export TAPENADE_URL=http://www-sop.inria.fr/ecuador/tapenade/distrib/tapenade_3.16.tar
            export TAPENADE_HOME=$(pwd)/tapenade_${{ parameters.TAPENADE_VERSION }}/bin
          fi

          wget $TAPENADE_URL
          tar -xzf tapenade_${{ parameters.TAPENADE_VERSION }}.tar
          export PATH=$TAPENADE_HOME/bin:$PATH
          ls && pwd
          cd ${{ parameters.REPO_NAME }}
          bash ${{ parameters.TAPENADE_SCRIPT }}
          git diff --exit-code
